apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-demo-sync
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-sync
  project: default
  source:
    repoURL: https://github.com/Vincoll/argocd-workshop
    path: k8s-manifests/raw
    targetRevision: dev
  syncPolicy:
    automated: # Activated
      prune: true
      selfHeal: false # FALSE
    syncOptions:
      - CreateNamespace=true
---