apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: makeademo
  name: makeademo-makeademo
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: makeademo
  name: makeademo-server
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: server
    app.kubernetes.io/name: makeademo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app:  server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 2
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: Always
        name: server
        resources:
          limits:
            memory: 30Mi
          requests:
            cpu: 10m
            memory: 30Mi
