apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: nginx:alpine
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "10m"
              memory: 30Mi
            limits:
              memory: 30Mi
